#PROJECT - GUI Keyboard
# -*- coding: utf-8 -*-

from PyQt4 import QtCore, QtGui
import sys

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)


class Ui_keyboard(QtGui.QWidget):
    
    #initialisation
    def __init__(self):
        QtGui.QWidget.__init__(self)
        self.setupUi(self)

    #button object creation with req dimensions wiht the help of QT4 designer
    def setupUi(self, keyboard):
        keyboard.setObjectName(_fromUtf8("keyboard"))
        keyboard.setEnabled(True)
        keyboard.resize(864, 305)
        self.oneButton = QtGui.QPushButton(keyboard)
        self.oneButton.setGeometry(QtCore.QRect(10, 80, 60, 40))
        self.oneButton.setWhatsThis(_fromUtf8(""))
        self.oneButton.setAutoFillBackground(False)
        self.oneButton.setCheckable(False)
        self.oneButton.setAutoDefault(False)
        self.oneButton.setDefault(False)
        self.oneButton.setFlat(False)
        self.oneButton.setObjectName(_fromUtf8("oneButton"))
        self.sixButton = QtGui.QPushButton(keyboard)
        self.sixButton.setGeometry(QtCore.QRect(310, 80, 60, 40))
        self.sixButton.setAutoDefault(False)
        self.sixButton.setObjectName(_fromUtf8("sixButton"))
        self.fourButton = QtGui.QPushButton(keyboard)
        self.fourButton.setGeometry(QtCore.QRect(190, 80, 60, 40))
        self.fourButton.setAutoDefault(False)
        self.fourButton.setObjectName(_fromUtf8("fourButton"))
        self.twoButton = QtGui.QPushButton(keyboard)
        self.twoButton.setGeometry(QtCore.QRect(70, 80, 60, 40))
        self.twoButton.setWhatsThis(_fromUtf8(""))
        self.twoButton.setAutoFillBackground(False)
        self.twoButton.setCheckable(False)
        self.twoButton.setAutoDefault(False)
        self.twoButton.setDefault(False)
        self.twoButton.setFlat(False)
        self.twoButton.setObjectName(_fromUtf8("twoButton"))
        self.zeroButton = QtGui.QPushButton(keyboard)
        self.zeroButton.setGeometry(QtCore.QRect(550, 80, 60, 40))
        self.zeroButton.setAutoDefault(False)
        self.zeroButton.setObjectName(_fromUtf8("zeroButton"))
        self.eightButton = QtGui.QPushButton(keyboard)
        self.eightButton.setGeometry(QtCore.QRect(430, 80, 60, 40))
        self.eightButton.setAutoDefault(False)
        self.eightButton.setObjectName(_fromUtf8("eightButton"))
        self.sevenButton = QtGui.QPushButton(keyboard)
        self.sevenButton.setGeometry(QtCore.QRect(370, 80, 60, 40))
        self.sevenButton.setAutoDefault(False)
        self.sevenButton.setObjectName(_fromUtf8("sevenButton"))
        self.nineButton = QtGui.QPushButton(keyboard)
        self.nineButton.setGeometry(QtCore.QRect(490, 80, 60, 40))
        self.nineButton.setAutoDefault(False)
        self.nineButton.setObjectName(_fromUtf8("nineButton"))
        self.fiveButton = QtGui.QPushButton(keyboard)
        self.fiveButton.setGeometry(QtCore.QRect(250, 80, 60, 40))
        self.fiveButton.setAutoDefault(False)
        self.fiveButton.setObjectName(_fromUtf8("fiveButton"))
        self.threeButton = QtGui.QPushButton(keyboard)
        self.threeButton.setGeometry(QtCore.QRect(130, 80, 60, 40))
        self.threeButton.setAutoDefault(False)
        self.threeButton.setObjectName(_fromUtf8("threeButton"))
        self.e_Button = QtGui.QPushButton(keyboard)
        self.e_Button.setGeometry(QtCore.QRect(130, 120, 60, 40))
        self.e_Button.setAutoDefault(False)
        self.e_Button.setObjectName(_fromUtf8("e_Button"))
        self.q_Button = QtGui.QPushButton(keyboard)
        self.q_Button.setGeometry(QtCore.QRect(10, 120, 60, 40))
        self.q_Button.setAutoDefault(False)
        self.q_Button.setObjectName(_fromUtf8("q_Button"))
        self.w_Button = QtGui.QPushButton(keyboard)
        self.w_Button.setGeometry(QtCore.QRect(70, 120, 60, 40))
        self.w_Button.setAutoDefault(False)
        self.w_Button.setObjectName(_fromUtf8("w_Button"))
        self.r_Button = QtGui.QPushButton(keyboard)
        self.r_Button.setGeometry(QtCore.QRect(190, 120, 60, 40))
        self.r_Button.setAutoDefault(False)
        self.r_Button.setObjectName(_fromUtf8("r_Button"))
        self.t_Button = QtGui.QPushButton(keyboard)
        self.t_Button.setGeometry(QtCore.QRect(250, 120, 60, 40))
        self.t_Button.setAutoDefault(False)
        self.t_Button.setObjectName(_fromUtf8("t_Button"))
        self.y_Button = QtGui.QPushButton(keyboard)
        self.y_Button.setGeometry(QtCore.QRect(310, 120, 60, 40))
        self.y_Button.setAutoDefault(False)
        self.y_Button.setObjectName(_fromUtf8("y_Button"))
        self.u_Button = QtGui.QPushButton(keyboard)
        self.u_Button.setGeometry(QtCore.QRect(370, 120, 60, 40))
        self.u_Button.setAutoDefault(False)
        self.u_Button.setObjectName(_fromUtf8("u_Button"))
        self.i_Button = QtGui.QPushButton(keyboard)
        self.i_Button.setGeometry(QtCore.QRect(430, 120, 60, 40))
        self.i_Button.setAutoDefault(False)
        self.i_Button.setObjectName(_fromUtf8("i_Button"))
        self.o_Button = QtGui.QPushButton(keyboard)
        self.o_Button.setGeometry(QtCore.QRect(490, 120, 60, 40))
        self.o_Button.setAutoDefault(False)
        self.o_Button.setObjectName(_fromUtf8("o_Button"))
        self.minusButton = QtGui.QPushButton(keyboard)
        self.minusButton.setGeometry(QtCore.QRect(610, 80, 60, 40))
        self.minusButton.setAutoDefault(False)
        self.minusButton.setObjectName(_fromUtf8("minusButton"))
        self.backspaceButton = QtGui.QPushButton(keyboard)
        self.backspaceButton.setGeometry(QtCore.QRect(730, 40, 121, 40))
        self.backspaceButton.setAutoDefault(False)
        self.backspaceButton.setObjectName(_fromUtf8("backspaceButton"))
        self.equalButton = QtGui.QPushButton(keyboard)
        self.equalButton.setGeometry(QtCore.QRect(670, 80, 60, 40))
        self.equalButton.setAutoDefault(False)
        self.equalButton.setObjectName(_fromUtf8("equalButton"))
        self.p_Button = QtGui.QPushButton(keyboard)
        self.p_Button.setGeometry(QtCore.QRect(550, 120, 60, 40))
        self.p_Button.setAutoDefault(False)
        self.p_Button.setObjectName(_fromUtf8("p_Button"))
        self.leftsquarebracketButton = QtGui.QPushButton(keyboard)
        self.leftsquarebracketButton.setGeometry(QtCore.QRect(610, 120, 60, 40))
        self.leftsquarebracketButton.setAutoDefault(False)
        self.leftsquarebracketButton.setObjectName(_fromUtf8("leftsquarebracketButton"))
        self.rightsquarebracketButton = QtGui.QPushButton(keyboard)
        self.rightsquarebracketButton.setGeometry(QtCore.QRect(670, 120, 60, 40))
        self.rightsquarebracketButton.setAutoDefault(False)
        self.rightsquarebracketButton.setObjectName(_fromUtf8("rightsquarebracketButton"))
        self.leftcurlybracketButton = QtGui.QPushButton(keyboard)
        self.leftcurlybracketButton.setGeometry(QtCore.QRect(730, 120, 60, 40))
        self.leftcurlybracketButton.setAutoDefault(False)
        self.leftcurlybracketButton.setObjectName(_fromUtf8("leftcurlybracketButton"))
        self.k_Button = QtGui.QPushButton(keyboard)
        self.k_Button.setGeometry(QtCore.QRect(430, 160, 60, 40))
        self.k_Button.setAutoDefault(False)
        self.k_Button.setObjectName(_fromUtf8("k_Button"))
        self.g_Button = QtGui.QPushButton(keyboard)
        self.g_Button.setGeometry(QtCore.QRect(250, 160, 60, 40))
        self.g_Button.setAutoDefault(False)
        self.g_Button.setObjectName(_fromUtf8("g_Button"))
        self.s_Button = QtGui.QPushButton(keyboard)
        self.s_Button.setGeometry(QtCore.QRect(70, 160, 60, 40))
        self.s_Button.setAutoDefault(False)
        self.s_Button.setObjectName(_fromUtf8("s_Button"))
        self.a_Button = QtGui.QPushButton(keyboard)
        self.a_Button.setGeometry(QtCore.QRect(10, 160, 60, 40))
        self.a_Button.setAutoDefault(False)
        self.a_Button.setObjectName(_fromUtf8("a_Button"))
        self.colonButton = QtGui.QPushButton(keyboard)
        self.colonButton.setGeometry(QtCore.QRect(550, 160, 60, 40))
        self.colonButton.setAutoDefault(False)
        self.colonButton.setObjectName(_fromUtf8("colonButton"))
        self.h_Button = QtGui.QPushButton(keyboard)
        self.h_Button.setGeometry(QtCore.QRect(310, 160, 60, 40))
        self.h_Button.setAutoDefault(False)
        self.h_Button.setObjectName(_fromUtf8("h_Button"))
        self.j_Button = QtGui.QPushButton(keyboard)
        self.j_Button.setGeometry(QtCore.QRect(370, 160, 60, 40))
        self.j_Button.setAutoDefault(False)
        self.j_Button.setObjectName(_fromUtf8("j_Button"))
        self.l_Button = QtGui.QPushButton(keyboard)
        self.l_Button.setGeometry(QtCore.QRect(490, 160, 60, 40))
        self.l_Button.setAutoDefault(False)
        self.l_Button.setObjectName(_fromUtf8("l_Button"))
        self.semicolonButton = QtGui.QPushButton(keyboard)
        self.semicolonButton.setGeometry(QtCore.QRect(610, 160, 60, 40))
        self.semicolonButton.setAutoDefault(False)
        self.semicolonButton.setObjectName(_fromUtf8("semicolonButton"))
        self.d_Button = QtGui.QPushButton(keyboard)
        self.d_Button.setGeometry(QtCore.QRect(130, 160, 60, 40))
        self.d_Button.setAutoDefault(False)
        self.d_Button.setObjectName(_fromUtf8("d_Button"))
        self.f_Button = QtGui.QPushButton(keyboard)
        self.f_Button.setGeometry(QtCore.QRect(190, 160, 60, 40))
        self.f_Button.setAutoDefault(False)
        self.f_Button.setObjectName(_fromUtf8("f_Button"))
        self.c_Button = QtGui.QPushButton(keyboard)
        self.c_Button.setGeometry(QtCore.QRect(150, 200, 60, 40))
        self.c_Button.setAutoDefault(False)
        self.c_Button.setObjectName(_fromUtf8("c_Button"))
        self.m_Button = QtGui.QPushButton(keyboard)
        self.m_Button.setGeometry(QtCore.QRect(390, 200, 60, 40))
        self.m_Button.setAutoDefault(False)
        self.m_Button.setObjectName(_fromUtf8("m_Button"))
        self.z_Button = QtGui.QPushButton(keyboard)
        self.z_Button.setGeometry(QtCore.QRect(30, 200, 60, 40))
        self.z_Button.setAutoDefault(False)
        self.z_Button.setObjectName(_fromUtf8("z_Button"))
        self.v_Button = QtGui.QPushButton(keyboard)
        self.v_Button.setGeometry(QtCore.QRect(210, 200, 60, 40))
        self.v_Button.setAutoDefault(False)
        self.v_Button.setObjectName(_fromUtf8("v_Button"))
        self.dotButton = QtGui.QPushButton(keyboard)
        self.dotButton.setGeometry(QtCore.QRect(510, 200, 60, 40))
        self.dotButton.setAutoDefault(False)
        self.dotButton.setObjectName(_fromUtf8("dotButton"))
        self.x_Button = QtGui.QPushButton(keyboard)
        self.x_Button.setGeometry(QtCore.QRect(90, 200, 60, 40))
        self.x_Button.setAutoDefault(False)
        self.x_Button.setObjectName(_fromUtf8("x_Button"))
        self.n_Button = QtGui.QPushButton(keyboard)
        self.n_Button.setGeometry(QtCore.QRect(330, 200, 60, 40))
        self.n_Button.setAutoDefault(False)
        self.n_Button.setObjectName(_fromUtf8("n_Button"))
        self.b_Button = QtGui.QPushButton(keyboard)
        self.b_Button.setGeometry(QtCore.QRect(270, 200, 60, 40))
        self.b_Button.setAutoDefault(False)
        self.b_Button.setObjectName(_fromUtf8("b_Button"))
        self.commaButton = QtGui.QPushButton(keyboard)
        self.commaButton.setGeometry(QtCore.QRect(450, 200, 60, 40))
        self.commaButton.setAutoDefault(False)
        self.commaButton.setObjectName(_fromUtf8("commaButton"))
        self.backslashButton = QtGui.QPushButton(keyboard)
        self.backslashButton.setGeometry(QtCore.QRect(570, 200, 60, 40))
        self.backslashButton.setAutoDefault(False)
        self.backslashButton.setObjectName(_fromUtf8("backslashButton"))
        self.spaceButton = QtGui.QPushButton(keyboard)
        self.spaceButton.setGeometry(QtCore.QRect(110, 240, 531, 50))
        self.spaceButton.setAutoDefault(False)
        self.spaceButton.setObjectName(_fromUtf8("spaceButton"))
        self.rightarrowButton = QtGui.QPushButton(keyboard)
        self.rightarrowButton.setGeometry(QtCore.QRect(700, 240, 60, 50))
        self.rightarrowButton.setAutoDefault(False)
        self.rightarrowButton.setObjectName(_fromUtf8("rightarrowButton"))
        self.leftarrowButton = QtGui.QPushButton(keyboard)
        self.leftarrowButton.setGeometry(QtCore.QRect(640, 240, 60, 50))
        self.leftarrowButton.setAutoDefault(False)
        self.leftarrowButton.setObjectName(_fromUtf8("leftarrowButton"))
        self.questionButton = QtGui.QPushButton(keyboard)
        self.questionButton.setGeometry(QtCore.QRect(790, 160, 60, 40))
        self.questionButton.setAutoDefault(False)
        self.questionButton.setObjectName(_fromUtf8("questionButton"))
        self.leftanglebracketButton = QtGui.QPushButton(keyboard)
        self.leftanglebracketButton.setGeometry(QtCore.QRect(690, 200, 60, 40))
        self.leftanglebracketButton.setAutoDefault(False)
        self.leftanglebracketButton.setObjectName(_fromUtf8("leftanglebracketButton"))
        self.rightanglebracketButton = QtGui.QPushButton(keyboard)
        self.rightanglebracketButton.setGeometry(QtCore.QRect(750, 200, 60, 40))
        self.rightanglebracketButton.setAutoDefault(False)
        self.rightanglebracketButton.setObjectName(_fromUtf8("rightanglebracketButton"))
        self.doublequoteButton = QtGui.QPushButton(keyboard)
        self.doublequoteButton.setGeometry(QtCore.QRect(730, 160, 60, 40))
        self.doublequoteButton.setAutoDefault(False)
        self.doublequoteButton.setObjectName(_fromUtf8("doublequoteButton"))
        self.singlequoteButton = QtGui.QPushButton(keyboard)
        self.singlequoteButton.setGeometry(QtCore.QRect(670, 160, 60, 40))
        self.singlequoteButton.setAutoDefault(False)
        self.singlequoteButton.setObjectName(_fromUtf8("singlequoteButton"))
        self.rightcurlybracketButton = QtGui.QPushButton(keyboard)
        self.rightcurlybracketButton.setGeometry(QtCore.QRect(790, 120, 60, 40))
        self.rightcurlybracketButton.setAutoDefault(False)
        self.rightcurlybracketButton.setObjectName(_fromUtf8("rightcurlybracketButton"))
        self.forwardslashButton = QtGui.QPushButton(keyboard)
        self.forwardslashButton.setGeometry(QtCore.QRect(630, 200, 60, 40))
        self.forwardslashButton.setAutoDefault(False)
        self.forwardslashButton.setObjectName(_fromUtf8("forwardslashButton"))
        self.ampersandButton = QtGui.QPushButton(keyboard)
        self.ampersandButton.setGeometry(QtCore.QRect(370, 40, 60, 40))
        self.ampersandButton.setAutoDefault(False)
        self.ampersandButton.setObjectName(_fromUtf8("ampersandButton"))
        self.exclamationButton = QtGui.QPushButton(keyboard)
        self.exclamationButton.setGeometry(QtCore.QRect(10, 40, 60, 40))
        self.exclamationButton.setWhatsThis(_fromUtf8(""))
        self.exclamationButton.setAutoFillBackground(False)
        self.exclamationButton.setCheckable(False)
        self.exclamationButton.setAutoDefault(False)
        self.exclamationButton.setDefault(False)
        self.exclamationButton.setFlat(False)
        self.exclamationButton.setObjectName(_fromUtf8("exclamationButton"))
        self.atsignButton = QtGui.QPushButton(keyboard)
        self.atsignButton.setGeometry(QtCore.QRect(70, 40, 60, 40))
        self.atsignButton.setWhatsThis(_fromUtf8(""))
        self.atsignButton.setAutoFillBackground(False)
        self.atsignButton.setCheckable(False)
        self.atsignButton.setAutoDefault(False)
        self.atsignButton.setDefault(False)
        self.atsignButton.setFlat(False)
        self.atsignButton.setObjectName(_fromUtf8("atsignButton"))
        self.rightroundbracketButton = QtGui.QPushButton(keyboard)
        self.rightroundbracketButton.setGeometry(QtCore.QRect(550, 40, 60, 40))
        self.rightroundbracketButton.setAutoDefault(False)
        self.rightroundbracketButton.setObjectName(_fromUtf8("rightroundbracketButton"))
        self.percentButton = QtGui.QPushButton(keyboard)
        self.percentButton.setGeometry(QtCore.QRect(250, 40, 60, 40))
        self.percentButton.setAutoDefault(False)
        self.percentButton.setObjectName(_fromUtf8("percentButton"))
        self.dollarButton = QtGui.QPushButton(keyboard)
        self.dollarButton.setGeometry(QtCore.QRect(190, 40, 60, 40))
        self.dollarButton.setAutoDefault(False)
        self.dollarButton.setObjectName(_fromUtf8("dollarButton"))
        self.hashButton = QtGui.QPushButton(keyboard)
        self.hashButton.setGeometry(QtCore.QRect(130, 40, 60, 40))
        self.hashButton.setAutoDefault(False)
        self.hashButton.setObjectName(_fromUtf8("hashButton"))
        self.caretButton = QtGui.QPushButton(keyboard)
        self.caretButton.setGeometry(QtCore.QRect(310, 40, 60, 40))
        self.caretButton.setAutoDefault(False)
        self.caretButton.setObjectName(_fromUtf8("caretButton"))
        self.asteriskButton = QtGui.QPushButton(keyboard)
        self.asteriskButton.setGeometry(QtCore.QRect(430, 40, 60, 40))
        self.asteriskButton.setAutoDefault(False)
        self.asteriskButton.setObjectName(_fromUtf8("asteriskButton"))
        self.leftroundbracketButton = QtGui.QPushButton(keyboard)
        self.leftroundbracketButton.setGeometry(QtCore.QRect(490, 40, 60, 40))
        self.leftroundbracketButton.setAutoDefault(False)
        self.leftroundbracketButton.setObjectName(_fromUtf8("leftroundbracketButton"))
        self.underscoreButton = QtGui.QPushButton(keyboard)
        self.underscoreButton.setGeometry(QtCore.QRect(610, 40, 60, 40))
        self.underscoreButton.setAutoDefault(False)
        self.underscoreButton.setObjectName(_fromUtf8("underscoreButton"))
        self.plusButton = QtGui.QPushButton(keyboard)
        self.plusButton.setGeometry(QtCore.QRect(670, 40, 60, 40))
        self.plusButton.setAutoDefault(False)
        self.plusButton.setObjectName(_fromUtf8("plusButton"))
        self.clrButton = QtGui.QPushButton(keyboard)
        self.clrButton.setGeometry(QtCore.QRect(730, 80, 121, 40))
        self.clrButton.setAutoDefault(False)
        self.clrButton.setObjectName(_fromUtf8("clrButton"))
        self.lineEdit = QtGui.QLineEdit(keyboard)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 841, 27))
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))

        self.retranslateUi(keyboard)
        QtCore.QMetaObject.connectSlotsByName(keyboard)

    #button object name declaration and pressing functions
    def retranslateUi(self, keyboard):
        #window title name
        keyboard.setWindowTitle(_translate("keyboard", "Simple Keyboard", None))
        #buttons names
        self.oneButton.setText(_translate("keyboard", "1", None))
        self.sixButton.setText(_translate("keyboard", "6", None))
        self.fourButton.setText(_translate("keyboard", "4", None))
        self.twoButton.setText(_translate("keyboard", "2", None))
        self.zeroButton.setText(_translate("keyboard", "0", None))
        self.eightButton.setText(_translate("keyboard", "8", None))
        self.sevenButton.setText(_translate("keyboard", "7", None))
        self.nineButton.setText(_translate("keyboard", "9", None))
        self.fiveButton.setText(_translate("keyboard", "5", None))
        self.threeButton.setText(_translate("keyboard", "3", None))
        self.e_Button.setText(_translate("keyboard", "e", None))
        self.q_Button.setText(_translate("keyboard", "q", None))
        self.w_Button.setText(_translate("keyboard", "w", None))
        self.r_Button.setText(_translate("keyboard", "r", None))
        self.t_Button.setText(_translate("keyboard", "t", None))
        self.y_Button.setText(_translate("keyboard", "y", None))
        self.u_Button.setText(_translate("keyboard", "u", None))
        self.i_Button.setText(_translate("keyboard", "i", None))
        self.o_Button.setText(_translate("keyboard", "o", None))
        self.minusButton.setText(_translate("keyboard", "-", None))
        self.backspaceButton.setText(_translate("keyboard", "BACKSPACE", None))
        self.equalButton.setText(_translate("keyboard", "=", None))
        self.p_Button.setText(_translate("keyboard", "p", None))
        self.leftsquarebracketButton.setText(_translate("keyboard", "[", None))
        self.rightsquarebracketButton.setText(_translate("keyboard", "]", None))
        self.leftcurlybracketButton.setText(_translate("keyboard", "{", None))
        self.k_Button.setText(_translate("keyboard", "k", None))
        self.g_Button.setText(_translate("keyboard", "g", None))
        self.s_Button.setText(_translate("keyboard", "s", None))
        self.a_Button.setText(_translate("keyboard", "a", None))
        self.colonButton.setText(_translate("keyboard", ":", None))
        self.h_Button.setText(_translate("keyboard", "h", None))
        self.j_Button.setText(_translate("keyboard", "j", None))
        self.l_Button.setText(_translate("keyboard", "l", None))
        self.semicolonButton.setText(_translate("keyboard", ";", None))
        self.d_Button.setText(_translate("keyboard", "d", None))
        self.f_Button.setText(_translate("keyboard", "f", None))
        self.c_Button.setText(_translate("keyboard", "c", None))
        self.m_Button.setText(_translate("keyboard", "m", None))
        self.z_Button.setText(_translate("keyboard", "z", None))
        self.v_Button.setText(_translate("keyboard", "v", None))
        self.dotButton.setText(_translate("keyboard", ".", None))
        self.x_Button.setText(_translate("keyboard", "x", None))
        self.n_Button.setText(_translate("keyboard", "n", None))
        self.b_Button.setText(_translate("keyboard", "b", None))
        self.commaButton.setText(_translate("keyboard", ",", None))
        self.backslashButton.setText(_translate("keyboard", "/", None))
        self.spaceButton.setText(_translate("keyboard", "SPACEBAR", None))
        self.rightarrowButton.setText(_translate("keyboard", "→", None))
        self.leftarrowButton.setText(_translate("keyboard", "←", None))
        self.questionButton.setText(_translate("keyboard", "?", None))
        self.leftanglebracketButton.setText(_translate("keyboard", "<", None))
        self.rightanglebracketButton.setText(_translate("keyboard", ">", None))
        self.doublequoteButton.setText(_translate("keyboard", "\"", None))
        self.singlequoteButton.setText(_translate("keyboard", "\'", None))
        self.rightcurlybracketButton.setText(_translate("keyboard", "}", None))
        self.forwardslashButton.setText(_translate("keyboard", "\\", None))
        self.ampersandButton.setText(_translate("keyboard", "&&", None))
        self.exclamationButton.setText(_translate("keyboard", "!", None))
        self.atsignButton.setText(_translate("keyboard", "@", None))
        self.rightroundbracketButton.setText(_translate("keyboard", ")", None))
        self.percentButton.setText(_translate("keyboard", "%", None))
        self.dollarButton.setText(_translate("keyboard", "$", None))
        self.hashButton.setText(_translate("keyboard", "#", None))
        self.caretButton.setText(_translate("keyboard", "^", None))
        self.asteriskButton.setText(_translate("keyboard", "*", None))
        self.leftroundbracketButton.setText(_translate("keyboard", "(", None))
        self.underscoreButton.setText(_translate("keyboard", "_", None))
        self.plusButton.setText(_translate("keyboard", "+", None))
        self.clrButton.setText(_translate("keyboard", "CLR", None))

        #function to click the req button and proceed that button's functionality
        self.oneButton.clicked.connect(self.One)
        self.twoButton.clicked.connect(self.Two)
        self.threeButton.clicked.connect(self.Three)
        self.fourButton.clicked.connect(self.Four)
        self.fiveButton.clicked.connect(self.Five)
        self.sixButton.clicked.connect(self.Six)
        self.sevenButton.clicked.connect(self.Seven)
        self.eightButton.clicked.connect(self.Eight)
        self.nineButton.clicked.connect(self.Nine)
        self.zeroButton.clicked.connect(self.Zero)
        self.a_Button.clicked.connect(self.a)
        self.b_Button.clicked.connect(self.b)
        self.c_Button.clicked.connect(self.c)
        self.d_Button.clicked.connect(self.d)
        self.e_Button.clicked.connect(self.e)
        self.f_Button.clicked.connect(self.f)
        self.g_Button.clicked.connect(self.g)
        self.h_Button.clicked.connect(self.h)
        self.i_Button.clicked.connect(self.i)
        self.j_Button.clicked.connect(self.j)
        self.k_Button.clicked.connect(self.k)
        self.l_Button.clicked.connect(self.l)
        self.m_Button.clicked.connect(self.m)
        self.n_Button.clicked.connect(self.n)
        self.o_Button.clicked.connect(self.o)
        self.p_Button.clicked.connect(self.p)
        self.q_Button.clicked.connect(self.q)
        self.r_Button.clicked.connect(self.r)
        self.s_Button.clicked.connect(self.s)
        self.t_Button.clicked.connect(self.t)
        self.u_Button.clicked.connect(self.u)
        self.v_Button.clicked.connect(self.v)
        self.w_Button.clicked.connect(self.w)
        self.x_Button.clicked.connect(self.x)
        self.y_Button.clicked.connect(self.y)
        self.z_Button.clicked.connect(self.z)
        self.exclamationButton.clicked.connect(self.Exclamation)
        self.atsignButton.clicked.connect(self.Atsign)
        self.hashButton.clicked.connect(self.Hash)
        self.dollarButton.clicked.connect(self.Dollar)
        self.percentButton.clicked.connect(self.Percent)
        self.caretButton.clicked.connect(self.Caret)
        self.ampersandButton.clicked.connect(self.Ampersand)
        self.asteriskButton.clicked.connect(self.Asterisk)
        self.leftroundbracketButton.clicked.connect(self.LRB)
        self.rightroundbracketButton.clicked.connect(self.RRB)
        self.underscoreButton.clicked.connect(self.Under)
        self.plusButton.clicked.connect(self.Plus)
        self.minusButton.clicked.connect(self.Minus)
        self.equalButton.clicked.connect(self.Equal)
        self.leftsquarebracketButton.clicked.connect(self.LSB)
        self.rightsquarebracketButton.clicked.connect(self.RSB)
        self.leftcurlybracketButton.clicked.connect(self.LCB)
        self.rightcurlybracketButton.clicked.connect(self.RCB)
        self.leftanglebracketButton.clicked.connect(self.LAB)
        self.rightanglebracketButton.clicked.connect(self.RAB)
        self.singlequoteButton.clicked.connect(self.Quote)
        self.doublequoteButton.clicked.connect(self.Quotes)
        self.questionButton.clicked.connect(self.Ques)
        self.colonButton.clicked.connect(self.Colon)
        self.semicolonButton.clicked.connect(self.SColon)
        self.commaButton.clicked.connect(self.Comma)
        self.dotButton.clicked.connect(self.Dot)
        self.backslashButton.clicked.connect(self.BS)
        self.forwardslashButton.clicked.connect(self.FS)
        self.spaceButton.clicked.connect(self.Space)
        self.rightarrowButton.clicked.connect(self.Right)
        self.backspaceButton.clicked.connect(self.BSpace)
        self.leftarrowButton.clicked.connect(self.Left)
        self.clrButton.clicked.connect(self.Clr)


    #functions to input into the line edit section after 'clicked'

    ##numbers
    @QtCore.pyqtSlot()
    def One(self):
        self.lineEdit.insert("1")
    @QtCore.pyqtSlot()
    def Two(self):
        self.lineEdit.insert("2")
    @QtCore.pyqtSlot()
    def Three(self):
        self.lineEdit.insert("3")
    @QtCore.pyqtSlot()
    def Four(self):
        self.lineEdit.insert("4")
    @QtCore.pyqtSlot()
    def Five(self):
        self.lineEdit.insert("5")
    @QtCore.pyqtSlot()
    def Six(self):
        self.lineEdit.insert("6")
    @QtCore.pyqtSlot()
    def Seven(self):
        self.lineEdit.insert("7")
    @QtCore.pyqtSlot()
    def Eight(self):
        self.lineEdit.insert("8")
    @QtCore.pyqtSlot()
    def Nine(self):
        self.lineEdit.insert("9")
    def Zero(self):
        self.lineEdit.insert("0")
    @QtCore.pyqtSlot()

    ##letters
    def a(self):
        self.lineEdit.insert("a")
    @QtCore.pyqtSlot()
    def b(self):
        self.lineEdit.insert("b")
    @QtCore.pyqtSlot()
    def c(self):
        self.lineEdit.insert("c")
    @QtCore.pyqtSlot()
    def d(self):
        self.lineEdit.insert("d")
    @QtCore.pyqtSlot()
    def e(self):
        self.lineEdit.insert("e")
    @QtCore.pyqtSlot()
    def f(self):
        self.lineEdit.insert("f")
    @QtCore.pyqtSlot()
    def e(self):
        self.lineEdit.insert("e")
    @QtCore.pyqtSlot()
    def f(self):
        self.lineEdit.insert("f")
    @QtCore.pyqtSlot()
    def g(self):
        self.lineEdit.insert("g")
    @QtCore.pyqtSlot()
    def h(self):
        self.lineEdit.insert("h")
    @QtCore.pyqtSlot()
    def i(self):
        self.lineEdit.insert("i")
    @QtCore.pyqtSlot()
    def j(self):
        self.lineEdit.insert("j")
    @QtCore.pyqtSlot()
    def k(self):
        self.lineEdit.insert("k")
    @QtCore.pyqtSlot()
    def l(self):
        self.lineEdit.insert("l")
    @QtCore.pyqtSlot()
    def m(self):
        self.lineEdit.insert("m")
    @QtCore.pyqtSlot()
    def n(self):
        self.lineEdit.insert("n")
    @QtCore.pyqtSlot()
    def o(self):
        self.lineEdit.insert("o")
    @QtCore.pyqtSlot()
    def p(self):
        self.lineEdit.insert("p")
    @QtCore.pyqtSlot()
    def q(self):
        self.lineEdit.insert("q")
    @QtCore.pyqtSlot()
    def r(self):
        self.lineEdit.insert("r")
    @QtCore.pyqtSlot()
    def s(self):
        self.lineEdit.insert("s")
    @QtCore.pyqtSlot()
    def t(self):
        self.lineEdit.insert("t")
    @QtCore.pyqtSlot()
    def u(self):
        self.lineEdit.insert("u")
    @QtCore.pyqtSlot()
    def v(self):
        self.lineEdit.insert("v")
    @QtCore.pyqtSlot()
    def w(self):
        self.lineEdit.insert("w")
    @QtCore.pyqtSlot()
    def x(self):
        self.lineEdit.insert("x")
    @QtCore.pyqtSlot()
    def y(self):
        self.lineEdit.insert("y")
    @QtCore.pyqtSlot()
    def z(self):
        self.lineEdit.insert("z")

    ##symbols
    def Exclamation(self):
        self.lineEdit.insert("!")
    @QtCore.pyqtSlot()
    def Atsign(self):
        self.lineEdit.insert("@")
    @QtCore.pyqtSlot()
    def Hash(self):
        self.lineEdit.insert("#")
    @QtCore.pyqtSlot()
    def Dollar(self):
        self.lineEdit.insert("$")
    @QtCore.pyqtSlot()
    def Percent(self):
        self.lineEdit.insert("%")
    @QtCore.pyqtSlot()
    def Caret(self):
        self.lineEdit.insert("^")
    @QtCore.pyqtSlot()
    def Ampersand(self):
        self.lineEdit.insert("&")
    @QtCore.pyqtSlot()
    def Asterisk(self):
        self.lineEdit.insert("*")
    @QtCore.pyqtSlot()
    def LRB(self):
        self.lineEdit.insert("(")
    @QtCore.pyqtSlot()
    def RRB(self):
        self.lineEdit.insert(")")
    @QtCore.pyqtSlot()
    def Under(self):
        self.lineEdit.insert("_")
    @QtCore.pyqtSlot()
    def Plus(self):
        self.lineEdit.insert("+")
    @QtCore.pyqtSlot()
    def Minus(self):
        self.lineEdit.insert("-")
    @QtCore.pyqtSlot()
    def Equal(self):
        self.lineEdit.insert("=")
    @QtCore.pyqtSlot()
    def LSB(self):
        self.lineEdit.insert("[")
    @QtCore.pyqtSlot()
    def RSB(self):
        self.lineEdit.insert("]")
    @QtCore.pyqtSlot()
    def LCB(self):
        self.lineEdit.insert("{")
    @QtCore.pyqtSlot()
    def RCB(self):
        self.lineEdit.insert("}")
    @QtCore.pyqtSlot()
    def LAB(self):
        self.lineEdit.insert("<")
    @QtCore.pyqtSlot()
    def RAB(self):
        self.lineEdit.insert(">")
    @QtCore.pyqtSlot()
    def Quote(self):
        self.lineEdit.insert("\'")
    @QtCore.pyqtSlot()
    def Quotes(self):
        self.lineEdit.insert("\"")
    @QtCore.pyqtSlot()
    def Ques(self):
        self.lineEdit.insert("?")
    @QtCore.pyqtSlot()
    def Colon(self):
        self.lineEdit.insert(":")
    @QtCore.pyqtSlot()
    def SColon(self):
        self.lineEdit.insert(";")
    @QtCore.pyqtSlot()
    def Comma(self):
        self.lineEdit.insert(",")
    @QtCore.pyqtSlot()
    def Dot(self):
        self.lineEdit.insert(".")
    @QtCore.pyqtSlot()
    def BS(self):
        self.lineEdit.insert("/")
    def FS(self):
        self.lineEdit.insert("\\")
    def Space(self):
        self.lineEdit.insert(" ")

    #special
    def Clr(self):
        self.lineEdit.clear()

    def BSpace(self):
        self.lineEdit.backspace()

    def Left(self):
        self.lineEdit.cursorBackward(True,2)
        self.lineEdit.cursorForward(False,1)

    def Right(self):
        self.lineEdit.cursorForward(False,1)


#function to run the entire GUI app
def run():
    app = QtGui.QApplication(sys.argv)
    ex = Ui_keyboard()
    ex.show()
    sys.exit(app.exec_())

run()